### ISSUE TITLE
Mega Man Xtreme - Invisible Lava in Flame Stag Stage

### ISSUE THREAD

**Issue by Nam-Ereh-Won** [JoseJX/analogue-pocket-patches#20]
The lava is invisible in the second area of Flame Stag. I tested a physical copy of the game to rule out an issue with the Pocket itself.

**Comment by JoseJX** [comment]
I can reproduce this, I'll take a look and see if I can fix it. Thanks for reporting!

**Comment by JoseJX** [comment]
Just wanted to say that I haven't forgotten about this bug. It turned out that there were probably other graphical glitches that were present before as well and I'm working my way through them, it's just a bit tedious and I haven't figured it all out yet. I'm hoping to have a fixed version in the next few days.

**Comment by JoseJX** [comment]
I think this is fixed now, please feel free to re-open the bug if you have any more issues. Sorry for the wait!
