### ISSUE TITLE
File names for IPS files to include md5sum

### ISSUE THREAD

**Issue by amoore2600** [JoseJX/analogue-pocket-patches#32]
Please organize file names for IPS files to include md5sum. This makes scripting much easier to apply patches in bulk.

**Comment by JoseJX** [comment]
I have no idea what you're asking for exactly. Can you be more specific about what you're trying to do or what you're asking me to do? Every file I've released has an MD5 sum along with the patch.

**Comment by amoore2600** [comment]
Here's an example for a file name 007TWINE-1f1fb3cf8783f880bc796d667be60231.ips

With files names like this one can easily script patching files in batch.

**Comment by JoseJX** [comment]
Sorry, at this point, I don't think I'm interested in going back and changing all of these, especially since some of them apply to multiple MD5's. I think a better option would be for someone else (perhaps you?) to maintain a database of MD5s if this is something that people really want. Good luck and have fun!

**Comment by BestPig** [comment]
@amoore2600 You can maybe use this instead -> https://github.com/JonAbrams/retropatcher/blob/main/pages/api/patches.json
It has all our patches with the matching md5, so you should be able to script it ;)
