### ISSUE TITLE
Pop'n Music GB - Disney Tunes: Credits Graphics Corrupt

### ISSUE THREAD

**Issue by dotdissent** [JoseJX/analogue-pocket-patches#48]
Went in to the first mode, played through three songs. When the credits show, it flips between corrupted graphics and the actual credits.

Video: https://youtu.be/6dfjVoYie4c

**Comment by JoseJX** [comment]
I can reproduce these issues, sorry about that! I'll try to get to this tonight.

**Comment by JoseJX** [comment]
There was some menu corruption that I fixed in addition to the end credit issue. Please feel free to re-open this bug if you find any other issues! This one is a bit tough to work out and having known scenarios with issues really helps to debug it.

I believe though that the issues you brought up are fixed in commit 3f4aacea.

**Comment by dotdissent** [comment]
Thanks for your swift work!

Edit: By the way, if you have a donation box, let me know!
